Feature/news
CosmosTUe/Cosmos pull request #144
Opened 2021-07-10 14:09 UTC by bcvandendool

Add support for news articles

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-07-12 18:48 UTC, bcvandendool commented
Ill fix the white text issue in the add form in a later pull request, where ill fix up the looks of the gmm, news and photos forms to be more like to login form and such, but ill rather do that all at once, so it wont be in this pr.

2021-07-13 12:35 UTC, dasyad00 requested changes

2021-07-13 12:35 UTC, dasyad00 commented on cosmos/forms.py
> +            Field("member_only"),
"Member only" checkbox is still illegible

2021-07-13 13:02 UTC, dasyad00 approved these changes

2021-07-13 13:44 UTC, merged