Subpage titles
CosmosTUe/Cosmos pull request #21
Opened 2020-08-26 10:00 UTC by dasyad00

I'll do the titles for board subpage tonight

2020-08-26 12:24 UTC, bcvandendool commented on cosmos_cms/migrations/0004_committee_subpage_title.py
> +    ]
Remove these after squashing

2020-08-27 12:03 UTC, bcvandendool requested changes
Please use django-pipeline as can be seen in development

2020-08-27 12:46 UTC, maximekabel commented
The plugin asks to choose a committee but then it doesn't actually do anything with that model. It would be better if you have the plugin pull the name and the description from the committee model. Also right now you can upload any picture which means that it can come out too tall. I would recommend you force a certain aspect ratio when uploading.

2020-08-28 13:33 UTC, bcvandendool requested changes
Please also add the images of the board/committee. For example the image to the left, and to the right the name of the board/committee with the description underneath.

2020-08-29 15:41 UTC, dasyad00 commented
> Please also add the images of the board/committee. For example the image to the left, and to the right the name of the board/committee with the description underneath.

can you elaborate what you mean by this? I can't seem to find an example on the website https://punintendedinsta.wixsite.com/uwuwhatsthis/committee-subpage-template-v1

2020-08-30 18:56 UTC, bcvandendool requested changes
Spacing is fucked, its wider than the screen rn, and with container md it is also wider than the rest, something needs to be set different with the padding and margin. Furthermore can you try a 1:2 ratio of image:text, and see how that looks? i think that might look a bit better, not sure though.

2020-08-30 18:56 UTC, bcvandendool commented on cosmos/templates/base.html
> +    {% stylesheet "comm_title" %}
I dont think this is needed, is it?

2020-09-05 20:16 UTC, merged