Feature/door sensor
CosmosTUe/Cosmos pull request #230
Opened 2021-09-06 16:18 UTC by maximekabel

implemented door sensor

2021-09-07 06:14 UTC, dasyad00 approved these changes

2021-09-07 06:14 UTC, dasyad00 commented on cosmos/views.py
> +            print(os.environ.get("DOOR_STATUS", "0"))
can the print statements be removed prior to merging?

2021-09-07 17:58 UTC, bcvandendool requested changes

2021-09-07 17:58 UTC, bcvandendool commented on cosmos/models.py
> +    device = models.CharField(max_length=50)  # the target entity that uses this token
Unnecessary, only one device needed

2021-09-07 17:58 UTC, bcvandendool commented on cosmos/views.py
> +    door_status = int(os.environ.get("DOOR_STATUS", "0"))
pls no os environment stuff

2021-09-08 11:14 UTC, bcvandendool requested changes
Write tests

2021-09-08 12:09 UTC, merged