Beautify contacts
CosmosTUe/Cosmos pull request #25
Opened 2020-08-28 11:28 UTC by dasyad00

#24

2020-08-28 13:28 UTC, bcvandendool requested changes
Can you make the Message box larger, and put it next to the other inputs, so the box is less tall? The recipient box also needs to be a select, currently it is just a text box.

2020-08-29 15:17 UTC, dasyad00 commented
@bcvandendool missed your comment on changing the recipient box, will fix in upcoming commit

2020-08-29 16:30 UTC, bcvandendool requested changes

2020-08-29 16:30 UTC, bcvandendool commented on cosmos_cms/templates/cms/contacts/contact.html
>              {% if title %}<h3>{{ title }}</h3>{% endif %}
Center this

2020-08-29 18:32 UTC, bcvandendool approved these changes

2020-08-29 18:33 UTC, merged