Add ICal calendar feed for events + Hide past events
CosmosTUe/Cosmos pull request #256
Opened 2021-11-01 23:33 UTC by maximekabel

## Description
Add an ICal feed for events + hide past events on the events list

Fixes #

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have added tests to cover my changes.
- [x] All new code is fully covered by tests (see coverage report)

2021-11-03 18:58 UTC, bcvandendool requested changes
What is the feed going to be used for btw?

2021-11-03 18:58 UTC, bcvandendool commented on apps/events/views.py
> +        )
Do we not want previous events to be able to be seen at all? Maybe sth similar to the photos section that allows them to still be seen when going to the past? Cause only showing upcoming events at first makes sense, but i feel there is a better solution then removing them altogether.

2021-11-20 19:27 UTC, dasyad00 requested changes
pls also fix webpage titles

2021-11-20 19:27 UTC, dasyad00 commented on apps/events/models.py
> +        return "https://cosmostue.nl" + reverse("cosmos_events:events-view", kwargs={"pk": self.pk})
The server should be independent of the host domain. Refer to other instances of `get_absolute_url()` in the repo.

2021-11-26 13:00 UTC, dasyad00 approved these changes

2021-11-29 23:22 UTC, merged